// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace BlasSharp.AppleAccelerate
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "/System/Library/Frameworks/Accelerate.framework/Accelerate";



        [DllImport(__DllName, EntryPoint = "cblas_errprn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cblas_errprn(int __ierr, int __info, byte* __form);

        [DllImport(__DllName, EntryPoint = "cblas_xerbla", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_xerbla(int __p, byte* __rout, byte* __form);

        [DllImport(__DllName, EntryPoint = "cblas_sdsdot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float cblas_sdsdot(int __N, float __alpha, float* __X, int __incX, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dsdot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cblas_dsdot(int __N, float* __X, int __incX, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_sdot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float cblas_sdot(int __N, float* __X, int __incX, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_ddot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cblas_ddot(int __N, double* __X, int __incX, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_cdotu_sub", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cdotu_sub(int __N, void* __X, int __incX, void* __Y, int __incY, void* __dotu);

        [DllImport(__DllName, EntryPoint = "cblas_cdotc_sub", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cdotc_sub(int __N, void* __X, int __incX, void* __Y, int __incY, void* __dotc);

        [DllImport(__DllName, EntryPoint = "cblas_zdotu_sub", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zdotu_sub(int __N, void* __X, int __incX, void* __Y, int __incY, void* __dotu);

        [DllImport(__DllName, EntryPoint = "cblas_zdotc_sub", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zdotc_sub(int __N, void* __X, int __incX, void* __Y, int __incY, void* __dotc);

        [DllImport(__DllName, EntryPoint = "cblas_snrm2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float cblas_snrm2(int __N, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_sasum", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float cblas_sasum(int __N, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dnrm2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cblas_dnrm2(int __N, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dasum", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cblas_dasum(int __N, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_scnrm2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float cblas_scnrm2(int __N, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_scasum", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float cblas_scasum(int __N, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dznrm2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cblas_dznrm2(int __N, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dzasum", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cblas_dzasum(int __N, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_isamax", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cblas_isamax(int __N, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_idamax", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cblas_idamax(int __N, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_icamax", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cblas_icamax(int __N, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_izamax", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cblas_izamax(int __N, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_sswap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sswap(int __N, float* __X, int __incX, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_scopy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_scopy(int __N, float* __X, int __incX, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_saxpy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_saxpy(int __N, float __alpha, float* __X, int __incX, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dswap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dswap(int __N, double* __X, int __incX, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dcopy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dcopy(int __N, double* __X, int __incX, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_daxpy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_daxpy(int __N, double __alpha, double* __X, int __incX, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_cswap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cswap(int __N, void* __X, int __incX, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_ccopy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ccopy(int __N, void* __X, int __incX, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_caxpy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_caxpy(int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zswap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zswap(int __N, void* __X, int __incX, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zcopy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zcopy(int __N, void* __X, int __incX, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zaxpy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zaxpy(int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_srotg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_srotg(float* __a, float* __b, float* __c, float* __s);

        [DllImport(__DllName, EntryPoint = "cblas_srotmg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_srotmg(float* __d1, float* __d2, float* __b1, float __b2, float* __P);

        [DllImport(__DllName, EntryPoint = "cblas_srot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_srot(int __N, float* __X, int __incX, float* __Y, int __incY, float __c, float __s);

        [DllImport(__DllName, EntryPoint = "cblas_srotm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_srotm(int __N, float* __X, int __incX, float* __Y, int __incY, float* __P);

        [DllImport(__DllName, EntryPoint = "cblas_drotg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_drotg(double* __a, double* __b, double* __c, double* __s);

        [DllImport(__DllName, EntryPoint = "cblas_drotmg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_drotmg(double* __d1, double* __d2, double* __b1, double __b2, double* __P);

        [DllImport(__DllName, EntryPoint = "cblas_drot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_drot(int __N, double* __X, int __incX, double* __Y, int __incY, double __c, double __s);

        [DllImport(__DllName, EntryPoint = "cblas_drotm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_drotm(int __N, double* __X, int __incX, double* __Y, int __incY, double* __P);

        [DllImport(__DllName, EntryPoint = "cblas_sscal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sscal(int __N, float __alpha, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dscal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dscal(int __N, double __alpha, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_cscal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cscal(int __N, void* __alpha, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_zscal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zscal(int __N, void* __alpha, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_csscal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_csscal(int __N, float __alpha, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_zdscal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zdscal(int __N, double __alpha, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_crotg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_crotg(void* __a, void* __b, void* __c, void* __s);

        [DllImport(__DllName, EntryPoint = "cblas_zrotg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zrotg(void* __a, void* __b, void* __c, void* __s);

        [DllImport(__DllName, EntryPoint = "cblas_csrot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_csrot(int __N, void* __X, int __incX, void* __Y, int __incY, float __c, float __s);

        [DllImport(__DllName, EntryPoint = "cblas_zdrot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zdrot(int __N, void* __X, int __incX, void* __Y, int __incY, double __c, double __s);

        [DllImport(__DllName, EntryPoint = "cblas_sgemv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sgemv(uint __Order, uint __TransA, int __M, int __N, float __alpha, float* __A, int __lda, float* __X, int __incX, float __beta, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_sgbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sgbmv(uint __Order, uint __TransA, int __M, int __N, int __KL, int __KU, float __alpha, float* __A, int __lda, float* __X, int __incX, float __beta, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_strmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_strmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, float* __A, int __lda, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_stbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_stbmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, float* __A, int __lda, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_stpmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_stpmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, float* __Ap, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_strsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_strsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, float* __A, int __lda, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_stbsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_stbsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, float* __A, int __lda, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_stpsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_stpsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, float* __Ap, float* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dgemv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dgemv(uint __Order, uint __TransA, int __M, int __N, double __alpha, double* __A, int __lda, double* __X, int __incX, double __beta, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dgbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dgbmv(uint __Order, uint __TransA, int __M, int __N, int __KL, int __KU, double __alpha, double* __A, int __lda, double* __X, int __incX, double __beta, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dtrmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtrmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, double* __A, int __lda, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dtbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtbmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, double* __A, int __lda, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dtpmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtpmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, double* __Ap, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dtrsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtrsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, double* __A, int __lda, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dtbsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtbsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, double* __A, int __lda, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_dtpsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtpsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, double* __Ap, double* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_cgemv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cgemv(uint __Order, uint __TransA, int __M, int __N, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_cgbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cgbmv(uint __Order, uint __TransA, int __M, int __N, int __KL, int __KU, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_ctrmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctrmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ctbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctbmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ctpmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctpmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __Ap, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ctrsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctrsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ctbsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctbsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ctpsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctpsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __Ap, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_zgemv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zgemv(uint __Order, uint __TransA, int __M, int __N, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zgbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zgbmv(uint __Order, uint __TransA, int __M, int __N, int __KL, int __KU, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_ztrmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztrmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ztbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztbmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ztpmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztpmv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __Ap, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ztrsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztrsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ztbsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztbsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, int __K, void* __A, int __lda, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ztpsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztpsv(uint __Order, uint __Uplo, uint __TransA, uint __Diag, int __N, void* __Ap, void* __X, int __incX);

        [DllImport(__DllName, EntryPoint = "cblas_ssymv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssymv(uint __Order, uint __Uplo, int __N, float __alpha, float* __A, int __lda, float* __X, int __incX, float __beta, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_ssbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssbmv(uint __Order, uint __Uplo, int __N, int __K, float __alpha, float* __A, int __lda, float* __X, int __incX, float __beta, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_sspmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sspmv(uint __Order, uint __Uplo, int __N, float __alpha, float* __Ap, float* __X, int __incX, float __beta, float* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_sger", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sger(uint __Order, int __M, int __N, float __alpha, float* __X, int __incX, float* __Y, int __incY, float* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_ssyr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssyr(uint __Order, uint __Uplo, int __N, float __alpha, float* __X, int __incX, float* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_sspr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sspr(uint __Order, uint __Uplo, int __N, float __alpha, float* __X, int __incX, float* __Ap);

        [DllImport(__DllName, EntryPoint = "cblas_ssyr2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssyr2(uint __Order, uint __Uplo, int __N, float __alpha, float* __X, int __incX, float* __Y, int __incY, float* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_sspr2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sspr2(uint __Order, uint __Uplo, int __N, float __alpha, float* __X, int __incX, float* __Y, int __incY, float* __A);

        [DllImport(__DllName, EntryPoint = "cblas_dsymv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsymv(uint __Order, uint __Uplo, int __N, double __alpha, double* __A, int __lda, double* __X, int __incX, double __beta, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dsbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsbmv(uint __Order, uint __Uplo, int __N, int __K, double __alpha, double* __A, int __lda, double* __X, int __incX, double __beta, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dspmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dspmv(uint __Order, uint __Uplo, int __N, double __alpha, double* __Ap, double* __X, int __incX, double __beta, double* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_dger", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dger(uint __Order, int __M, int __N, double __alpha, double* __X, int __incX, double* __Y, int __incY, double* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_dsyr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsyr(uint __Order, uint __Uplo, int __N, double __alpha, double* __X, int __incX, double* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_dspr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dspr(uint __Order, uint __Uplo, int __N, double __alpha, double* __X, int __incX, double* __Ap);

        [DllImport(__DllName, EntryPoint = "cblas_dsyr2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsyr2(uint __Order, uint __Uplo, int __N, double __alpha, double* __X, int __incX, double* __Y, int __incY, double* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_dspr2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dspr2(uint __Order, uint __Uplo, int __N, double __alpha, double* __X, int __incX, double* __Y, int __incY, double* __A);

        [DllImport(__DllName, EntryPoint = "cblas_chemv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_chemv(uint __Order, uint __Uplo, int __N, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_chbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_chbmv(uint __Order, uint __Uplo, int __N, int __K, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_chpmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_chpmv(uint __Order, uint __Uplo, int __N, void* __alpha, void* __Ap, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_cgeru", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cgeru(uint __Order, int __M, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_cgerc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cgerc(uint __Order, int __M, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_cher", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cher(uint __Order, uint __Uplo, int __N, float __alpha, void* __X, int __incX, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_chpr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_chpr(uint __Order, uint __Uplo, int __N, float __alpha, void* __X, int __incX, void* __A);

        [DllImport(__DllName, EntryPoint = "cblas_cher2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cher2(uint __Order, uint __Uplo, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_chpr2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_chpr2(uint __Order, uint __Uplo, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __Ap);

        [DllImport(__DllName, EntryPoint = "cblas_zhemv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zhemv(uint __Order, uint __Uplo, int __N, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zhbmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zhbmv(uint __Order, uint __Uplo, int __N, int __K, void* __alpha, void* __A, int __lda, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zhpmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zhpmv(uint __Order, uint __Uplo, int __N, void* __alpha, void* __Ap, void* __X, int __incX, void* __beta, void* __Y, int __incY);

        [DllImport(__DllName, EntryPoint = "cblas_zgeru", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zgeru(uint __Order, int __M, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_zgerc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zgerc(uint __Order, int __M, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_zher", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zher(uint __Order, uint __Uplo, int __N, double __alpha, void* __X, int __incX, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_zhpr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zhpr(uint __Order, uint __Uplo, int __N, double __alpha, void* __X, int __incX, void* __A);

        [DllImport(__DllName, EntryPoint = "cblas_zher2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zher2(uint __Order, uint __Uplo, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __A, int __lda);

        [DllImport(__DllName, EntryPoint = "cblas_zhpr2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zhpr2(uint __Order, uint __Uplo, int __N, void* __alpha, void* __X, int __incX, void* __Y, int __incY, void* __Ap);

        [DllImport(__DllName, EntryPoint = "cblas_sgemm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_sgemm(uint __Order, uint __TransA, uint __TransB, int __M, int __N, int __K, float __alpha, float* __A, int __lda, float* __B, int __ldb, float __beta, float* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_ssymm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssymm(uint __Order, uint __Side, uint __Uplo, int __M, int __N, float __alpha, float* __A, int __lda, float* __B, int __ldb, float __beta, float* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_ssyrk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssyrk(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, float __alpha, float* __A, int __lda, float __beta, float* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_ssyr2k", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ssyr2k(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, float __alpha, float* __A, int __lda, float* __B, int __ldb, float __beta, float* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_strmm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_strmm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, float __alpha, float* __A, int __lda, float* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_strsm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_strsm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, float __alpha, float* __A, int __lda, float* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_dgemm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dgemm(uint __Order, uint __TransA, uint __TransB, int __M, int __N, int __K, double __alpha, double* __A, int __lda, double* __B, int __ldb, double __beta, double* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_dsymm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsymm(uint __Order, uint __Side, uint __Uplo, int __M, int __N, double __alpha, double* __A, int __lda, double* __B, int __ldb, double __beta, double* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_dsyrk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsyrk(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, double __alpha, double* __A, int __lda, double __beta, double* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_dsyr2k", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dsyr2k(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, double __alpha, double* __A, int __lda, double* __B, int __ldb, double __beta, double* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_dtrmm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtrmm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, double __alpha, double* __A, int __lda, double* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_dtrsm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_dtrsm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, double __alpha, double* __A, int __lda, double* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_cgemm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cgemm(uint __Order, uint __TransA, uint __TransB, int __M, int __N, int __K, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_csymm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_csymm(uint __Order, uint __Side, uint __Uplo, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_csyrk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_csyrk(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, void* __alpha, void* __A, int __lda, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_csyr2k", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_csyr2k(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_ctrmm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctrmm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_ctrsm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ctrsm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_zgemm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zgemm(uint __Order, uint __TransA, uint __TransB, int __M, int __N, int __K, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_zsymm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zsymm(uint __Order, uint __Side, uint __Uplo, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_zsyrk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zsyrk(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, void* __alpha, void* __A, int __lda, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_zsyr2k", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zsyr2k(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_ztrmm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztrmm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_ztrsm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_ztrsm(uint __Order, uint __Side, uint __Uplo, uint __TransA, uint __Diag, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb);

        [DllImport(__DllName, EntryPoint = "cblas_chemm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_chemm(uint __Order, uint __Side, uint __Uplo, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_cherk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cherk(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, float __alpha, void* __A, int __lda, float __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_cher2k", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_cher2k(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, void* __alpha, void* __A, int __lda, void* __B, int __ldb, float __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_zhemm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zhemm(uint __Order, uint __Side, uint __Uplo, int __M, int __N, void* __alpha, void* __A, int __lda, void* __B, int __ldb, void* __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_zherk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zherk(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, double __alpha, void* __A, int __lda, double __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "cblas_zher2k", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cblas_zher2k(uint __Order, uint __Uplo, uint __Trans, int __N, int __K, void* __alpha, void* __A, int __lda, void* __B, int __ldb, double __beta, void* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "appleblas_sgeadd", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void appleblas_sgeadd(uint __order, uint __transA, uint __transB, int __m, int __n, float __alpha, float* __A, int __lda, float __beta, float* __B, int __ldb, float* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "appleblas_dgeadd", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void appleblas_dgeadd(uint __order, uint __transA, uint __transB, int __m, int __n, double __alpha, double* __A, int __lda, double __beta, double* __B, int __ldb, double* __C, int __ldc);

        [DllImport(__DllName, EntryPoint = "sparse_inner_product_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float sparse_inner_product_dense_float(ulong nz, float* x, long* indx, float* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_inner_product_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sparse_inner_product_dense_double(ulong nz, double* x, long* indx, double* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_inner_product_sparse_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float sparse_inner_product_sparse_float(ulong nzx, ulong nzy, float* x, long* indx, float* y, long* indy);

        [DllImport(__DllName, EntryPoint = "sparse_inner_product_sparse_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sparse_inner_product_sparse_double(ulong nzx, ulong nzy, double* x, long* indx, double* y, long* indy);

        [DllImport(__DllName, EntryPoint = "sparse_vector_add_with_scale_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sparse_vector_add_with_scale_dense_float(ulong nz, float alpha, float* x, long* indx, float* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_vector_add_with_scale_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sparse_vector_add_with_scale_dense_double(ulong nz, double alpha, double* x, long* indx, double* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_vector_norm_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float sparse_vector_norm_float(ulong nz, float* x, long* indx, uint norm);

        [DllImport(__DllName, EntryPoint = "sparse_vector_norm_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sparse_vector_norm_double(ulong nz, double* x, long* indx, uint norm);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_vector_product_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_vector_product_dense_float(uint transa, float alpha, sparse_m_float* A, float* x, long incx, float* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_vector_product_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_vector_product_dense_double(uint transa, double alpha, sparse_m_double* A, double* x, long incx, double* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_vector_triangular_solve_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_vector_triangular_solve_dense_float(uint transt, float alpha, sparse_m_float* T, float* x, long incx);

        [DllImport(__DllName, EntryPoint = "sparse_vector_triangular_solve_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_vector_triangular_solve_dense_double(uint transt, double alpha, sparse_m_double* T, double* x, long incx);

        [DllImport(__DllName, EntryPoint = "sparse_outer_product_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_outer_product_dense_float(ulong M, ulong N, ulong nz, float alpha, float* x, long incx, float* y, long* indy, sparse_m_float** C);

        [DllImport(__DllName, EntryPoint = "sparse_outer_product_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_outer_product_dense_double(ulong M, ulong N, ulong nz, double alpha, double* x, long incx, double* y, long* indy, sparse_m_double** C);

        [DllImport(__DllName, EntryPoint = "sparse_permute_rows_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_permute_rows_float(sparse_m_float* A, long* perm);

        [DllImport(__DllName, EntryPoint = "sparse_permute_rows_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_permute_rows_double(sparse_m_double* A, long* perm);

        [DllImport(__DllName, EntryPoint = "sparse_permute_cols_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_permute_cols_float(sparse_m_float* A, long* perm);

        [DllImport(__DllName, EntryPoint = "sparse_permute_cols_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_permute_cols_double(sparse_m_double* A, long* perm);

        [DllImport(__DllName, EntryPoint = "sparse_elementwise_norm_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float sparse_elementwise_norm_float(sparse_m_float* A, uint norm);

        [DllImport(__DllName, EntryPoint = "sparse_elementwise_norm_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sparse_elementwise_norm_double(sparse_m_double* A, uint norm);

        [DllImport(__DllName, EntryPoint = "sparse_operator_norm_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float sparse_operator_norm_float(sparse_m_float* A, uint norm);

        [DllImport(__DllName, EntryPoint = "sparse_operator_norm_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sparse_operator_norm_double(sparse_m_double* A, uint norm);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_trace_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float sparse_matrix_trace_float(sparse_m_float* A, long offset);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_trace_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sparse_matrix_trace_double(sparse_m_double* A, long offset);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_product_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_product_dense_float(uint order, uint transa, ulong n, float alpha, sparse_m_float* A, float* B, ulong ldb, float* C, ulong ldc);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_product_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_product_dense_double(uint order, uint transa, ulong n, double alpha, sparse_m_double* A, double* B, ulong ldb, double* C, ulong ldc);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_product_sparse_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_product_sparse_float(uint order, uint transa, float alpha, sparse_m_float* A, sparse_m_float* B, float* C, ulong ldc);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_product_sparse_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_product_sparse_double(uint order, uint transa, double alpha, sparse_m_double* A, sparse_m_double* B, double* C, ulong ldc);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_triangular_solve_dense_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_triangular_solve_dense_float(uint order, uint transt, ulong nrhs, float alpha, sparse_m_float* T, float* B, ulong ldb);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_triangular_solve_dense_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_triangular_solve_dense_double(uint order, uint transt, ulong nrhs, double alpha, sparse_m_double* T, double* B, ulong ldb);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_create_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sparse_m_float* sparse_matrix_create_float(ulong M, ulong N);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_create_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sparse_m_double* sparse_matrix_create_double(ulong M, ulong N);

        [DllImport(__DllName, EntryPoint = "sparse_insert_entry_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_entry_float(sparse_m_float* A, float val, long i, long j);

        [DllImport(__DllName, EntryPoint = "sparse_insert_entry_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_entry_double(sparse_m_double* A, double val, long i, long j);

        [DllImport(__DllName, EntryPoint = "sparse_insert_entries_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_entries_float(sparse_m_float* A, ulong N, float* val, long* indx, long* jndx);

        [DllImport(__DllName, EntryPoint = "sparse_insert_entries_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_entries_double(sparse_m_double* A, ulong N, double* val, long* indx, long* jndx);

        [DllImport(__DllName, EntryPoint = "sparse_insert_col_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_col_float(sparse_m_float* A, long j, ulong nz, float* val, long* indx);

        [DllImport(__DllName, EntryPoint = "sparse_insert_col_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_col_double(sparse_m_double* A, long j, ulong nz, double* val, long* indx);

        [DllImport(__DllName, EntryPoint = "sparse_insert_row_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_row_float(sparse_m_float* A, long i, ulong nz, float* val, long* jndx);

        [DllImport(__DllName, EntryPoint = "sparse_insert_row_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_row_double(sparse_m_double* A, long i, ulong nz, double* val, long* jndx);

        [DllImport(__DllName, EntryPoint = "sparse_extract_sparse_row_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_extract_sparse_row_float(sparse_m_float* A, long row, long column_start, long* column_end, ulong nz, float* val, long* jndx);

        [DllImport(__DllName, EntryPoint = "sparse_extract_sparse_row_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_extract_sparse_row_double(sparse_m_double* A, long row, long column_start, long* column_end, ulong nz, double* val, long* jndx);

        [DllImport(__DllName, EntryPoint = "sparse_extract_sparse_column_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_extract_sparse_column_float(sparse_m_float* A, long column, long row_start, long* row_end, ulong nz, float* val, long* indx);

        [DllImport(__DllName, EntryPoint = "sparse_extract_sparse_column_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_extract_sparse_column_double(sparse_m_double* A, long column, long row_start, long* row_end, ulong nz, double* val, long* indx);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_block_create_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sparse_m_float* sparse_matrix_block_create_float(ulong Mb, ulong Nb, ulong k, ulong l);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_block_create_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sparse_m_double* sparse_matrix_block_create_double(ulong Mb, ulong Nb, ulong k, ulong l);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_variable_block_create_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sparse_m_float* sparse_matrix_variable_block_create_float(ulong Mb, ulong Nb, ulong* K, ulong* L);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_variable_block_create_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sparse_m_double* sparse_matrix_variable_block_create_double(ulong Mb, ulong Nb, ulong* K, ulong* L);

        [DllImport(__DllName, EntryPoint = "sparse_insert_block_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_block_float(sparse_m_float* A, float* val, ulong row_stride, ulong col_stride, long bi, long bj);

        [DllImport(__DllName, EntryPoint = "sparse_insert_block_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_insert_block_double(sparse_m_double* A, double* val, ulong row_stride, ulong col_stride, long bi, long bj);

        [DllImport(__DllName, EntryPoint = "sparse_extract_block_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_extract_block_float(sparse_m_float* A, long bi, long bj, ulong row_stride, ulong col_stride, float* val);

        [DllImport(__DllName, EntryPoint = "sparse_extract_block_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_extract_block_double(sparse_m_double* A, long bi, long bj, ulong row_stride, ulong col_stride, double* val);

        [DllImport(__DllName, EntryPoint = "sparse_get_block_dimension_for_row", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_block_dimension_for_row(void* A, long i);

        [DllImport(__DllName, EntryPoint = "sparse_get_block_dimension_for_col", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_block_dimension_for_col(void* A, long j);

        [DllImport(__DllName, EntryPoint = "sparse_commit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_commit(void* A);

        [DllImport(__DllName, EntryPoint = "sparse_get_matrix_property", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_matrix_property(void* A, uint pname);

        [DllImport(__DllName, EntryPoint = "sparse_set_matrix_property", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_set_matrix_property(void* A, uint pname);

        [DllImport(__DllName, EntryPoint = "sparse_get_matrix_number_of_rows", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong sparse_get_matrix_number_of_rows(void* A);

        [DllImport(__DllName, EntryPoint = "sparse_get_matrix_number_of_columns", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong sparse_get_matrix_number_of_columns(void* A);

        [DllImport(__DllName, EntryPoint = "sparse_get_matrix_nonzero_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_matrix_nonzero_count(void* A);

        [DllImport(__DllName, EntryPoint = "sparse_get_matrix_nonzero_count_for_row", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_matrix_nonzero_count_for_row(void* A, long i);

        [DllImport(__DllName, EntryPoint = "sparse_get_matrix_nonzero_count_for_column", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_matrix_nonzero_count_for_column(void* A, long j);

        [DllImport(__DllName, EntryPoint = "sparse_matrix_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sparse_matrix_destroy(void* A);

        [DllImport(__DllName, EntryPoint = "sparse_get_vector_nonzero_count_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_vector_nonzero_count_float(ulong N, float* x, long incx);

        [DllImport(__DllName, EntryPoint = "sparse_get_vector_nonzero_count_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_get_vector_nonzero_count_double(ulong N, double* x, long incx);

        [DllImport(__DllName, EntryPoint = "sparse_pack_vector_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_pack_vector_float(ulong N, ulong nz, float* x, long incx, float* y, long* indy);

        [DllImport(__DllName, EntryPoint = "sparse_pack_vector_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CLong sparse_pack_vector_double(ulong N, ulong nz, double* x, long incx, double* y, long* indy);

        [DllImport(__DllName, EntryPoint = "sparse_unpack_vector_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sparse_unpack_vector_float(ulong N, ulong nz, [MarshalAs(UnmanagedType.U1)] bool zero, float* x, long* indx, float* y, long incy);

        [DllImport(__DllName, EntryPoint = "sparse_unpack_vector_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sparse_unpack_vector_double(ulong N, ulong nz, [MarshalAs(UnmanagedType.U1)] bool zero, double* x, long* indx, double* y, long incy);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sparse_m_float
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sparse_m_double
    {
        public fixed byte _unused[1];
    }



}
